name: Build and publish Enmity plugins

on:
  push:
    paths:
      - "**.js"
      - "**.json"
      - "**.ts"
      - ".github/workflows/build.yaml"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Noode
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "src/*/package-lock.json"
      - name: Building plugins
        run: |
          for plugin in src/*; do
            if [ "$(basename $plugin)" = "PluginTemplate" ]; then
              continue
            fi
            (
              cd $plugin
              mkdir -p dist
              npm install 
              npm run build
            )
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: plugins
          path: |
            src/*/dist/*.js
            src/*/dist/*.json
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: "!contains(github.event.head_commit.message, 'skip-publish')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: plugins
          path: plugins-artifact/
      - name: Flatten plugins repository
        run: |
          mkdir -p plugins 
          find plugins-artifact -type f -name '*.js' -exec cp '{}' plugins \;
          find plugins-artifact -type f -name '*.json' -exec cp '{}' plugins \;
          rm -rf plugins-artifact
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.17"
      - name: Setup Enmity Store
        run: |
          mkdir -p $HOME/.enmity-store
          git clone https://github.com/itsnebulalol/enmity-store $HOME/.enmity-store
          (
            cd $HOME/.enmity-store
            go run cmds/store/main.go -name "Nebula's Enmity Plugins" -dir ${{ github.workspace }}
          )
          touch publish/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: publish
          git-config-name: GitHub Actions
          git-config-email: github-actions[bot]@users.noreply.github.com
          single-commit: true
